### ISSUE TITLE
Update for V2 API (V1 is deprecated on November 15, 2017)

### ISSUE THREAD

**Issue by parterburn** [ThanhKhoaIT/clarifai-rails#1]
Hey @ThanhKhoaIT are you planning on updating this to work with the V2 API by chance?

**Comment by gregschwartz** [comment]
*bump* Would love to use this instead of resorting to outright calling URLs!! 👍

**Comment by ThanhKhoaIT** [comment]
@parterburn, @gregschwartz V2 working now! Can you try.
https://rubygems.org/gems/clarifai-rails/versions/0.2.1
